[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = 'denops.vim'
hooks_file = '~/.vim/config/ddc.vim'


#ui
[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'
on_source = 'ddc.vim'


#source
[[plugins]]
repo = 'Shougo/ddc-source-copilot'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'
depends = ['vim-vsnip']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-shell_native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-shell'
on_source = 'ddc.vim'


#filter
[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_lsp_kind'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_kind_labels'
on_source = 'ddc.vim'
